version: "3.7"
services:
  twitter_discord_bot:
    build: ./
    image: twitter_discord_bot
    environment:
      TZ: Asia/Taipei
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./configs
        target: /usr/src/app/configs
