version: "3.7"
services:
  twitter_discord_bot:
    build: ./
    image: twitter_discord_bot
    environment:
      TZ: Asia/Taipei
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./last_id.ini
        target: /usr/src/app/last_id.ini
      - type: bind
        source: ./secret.ini
        target: /usr/src/app/secret.ini
      - type: bind
        source: ./twitter_users.txt
        target: /usr/src/app/twitter_users.txt
