name: Test TwitterDiscordBot

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install micropipenv
        micropipenv install --method pipenv
        pip install coverage

    - name: Test with unittest and generate test coverage
      run: |
        coverage run --source=twitter_discord_bot -m unittest -v
        coverage xml

    - uses: codecov/codecov-action@v1
      with:
        files: ./coverage.xml
